# Generated by Django 3.2.7 on 2021-09-17 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shopping_lists', '0001_initial'),
        ('recipe_ingredients', '0001_initial'),
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exclude', models.BooleanField(blank=True, default=False)),
                ('code_ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shopping_list_item', to='ingredients.ingredient', verbose_name='Ingredient')),
                ('code_recipe_ingredient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shopping_list_item', to='recipe_ingredients.recipeingredient', verbose_name='Recipe Ingredient')),
                ('code_shopping_list', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shopping_list_item', to='shopping_lists.shoppinglist', verbose_name='Shopping List')),
            ],
        ),
    ]
