# Generated by Django 3.2.7 on 2021-10-02 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list_items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglistitem',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
