# Generated by Django 3.2.7 on 2021-09-18 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list_items', '0003_shoppinglistitem_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppinglistitem',
            name='count',
        ),
    ]
