# Generated by Django 3.2.7 on 2021-09-18 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list_items', '0004_remove_shoppinglistitem_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppinglistitem',
            name='exclude',
        ),
        migrations.AddField(
            model_name='shoppinglistitem',
            name='add',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
