# Generated by Django 3.2.7 on 2021-09-18 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list_items', '0005_auto_20210918_1533'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppinglistitem',
            old_name='add',
            new_name='added',
        ),
    ]
