# Generated by Django 3.2.7 on 2021-10-03 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list_items', '0005_shoppinglistitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglistitem',
            name='day_of_week',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shoppinglistitem',
            name='meal',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
