# Generated by Django 3.2.7 on 2021-10-03 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list_items', '0006_auto_20211003_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppinglistitem',
            name='quantity',
        ),
    ]
