# Generated by Django 3.2.7 on 2021-10-10 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shopping_lists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_shopping_list', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='shared_accounts', to='shopping_lists.shoppinglist')),
                ('code_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='shared_accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
