# Generated by Django 3.2.7 on 2021-10-10 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedaccount',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
