# Generated by Django 3.2.7 on 2021-10-13 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccountName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('bool_main_user', models.BooleanField(default=False, verbose_name='Main User')),
                ('bool_permissions', models.BooleanField(default=False, verbose_name='Permissions')),
                ('code_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='user_account', to=settings.AUTH_USER_MODEL)),
                ('code_user_account', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='user_account', to='user_accounts.useraccountname')),
            ],
        ),
    ]
