# Generated by Django 3.2.7 on 2021-10-16 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='image_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
