# Generated by Django 3.2.7 on 2021-10-09 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='code_category',
        ),
        migrations.AddField(
            model_name='meal',
            name='meal_category',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
