# Generated by Django 3.2.7 on 2021-10-28 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_meal_image_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='image',
        ),
    ]
