# Generated by Django 3.2.7 on 2021-10-10 08:14

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_alter_meal_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, max_length=255, quality=75, size=[300, 300], upload_to='uploads/%Y/%m/%d'),
        ),
    ]
