# Generated by Django 3.2.7 on 2021-10-31 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_remove_meal_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='steps',
            field=models.TextField(blank=True, null=True, verbose_name='Cooking Instructions'),
        ),
    ]
