# Generated by Django 3.2.7 on 2021-10-03 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_categories', '0001_initial'),
        ('recipes', '0002_alter_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='code_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipe', to='recipe_categories.recipecategory', verbose_name='Category'),
        ),
    ]
