# Generated by Django 3.2.7 on 2021-10-16 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingredient_categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingredient', to='ingredient_categories.ingredientcategory', verbose_name='Category')),
            ],
        ),
    ]
