# Generated by Django 3.2.7 on 2021-10-03 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient_categories', '0001_initial'),
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='code_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='ingredient', to='ingredient_categories.ingredientcategory', verbose_name='Category'),
            preserve_default=False,
        ),
    ]
