# Generated by Django 3.2.7 on 2021-09-24 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='food_group',
        ),
    ]
