# Generated by Django 3.2.7 on 2021-10-09 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date_from', models.DateTimeField(blank=True, null=True, verbose_name='date from')),
                ('date_to', models.DateTimeField(blank=True, null=True, verbose_name='date to')),
                ('code_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='shopping_list', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
