# Generated by Django 3.2.7 on 2021-09-29 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_lists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='date_from',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date from'),
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='date_to',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date to'),
        ),
    ]
