# Generated by Django 3.2.7 on 2021-10-10 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_lists', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppinglist',
            name='code_user',
        ),
    ]
