# Generated by Django 3.2.7 on 2021-10-02 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_lists', '0002_auto_20210929_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='meal_from',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='meal_to',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
    ]
