# Generated by Django 3.2.7 on 2021-10-13 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0001_initial'),
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='code_user_account_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='user', to='user_accounts.useraccountname'),
        ),
    ]
