# Generated by Django 3.2.7 on 2022-06-18 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('colour', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('code_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='code_goal', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tracker Name')),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('code_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='code_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrackedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('code_goal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='code_tracker_item', to='tracker.goal')),
                ('code_tracker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='code_tracker_item', to='tracker.tracker')),
            ],
        ),
    ]
