# Generated by Django 3.2.7 on 2021-09-14 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipes', '0001_initial'),
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date_shop', models.DateField(blank=True, null=True)),
                ('done', models.BooleanField(blank=True, default=False)),
                ('code_ingredient', models.ManyToManyField(related_name='shopping_list', to='ingredients.Ingredient', verbose_name='Ingredient')),
                ('code_recipe', models.ManyToManyField(related_name='shopping_list', to='recipes.Recipe', verbose_name='Recipe')),
            ],
        ),
    ]
