# Generated by Django 3.2.7 on 2021-10-18 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_ingredients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealingredient',
            name='added',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
