# Generated by Django 3.2.7 on 2021-10-13 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meals', '0001_initial'),
        ('meal_ingredients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealingredient',
            name='code_meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meal_ingredient', to='meals.meal', verbose_name='Meal'),
        ),
    ]
