# Generated by Django 3.2.7 on 2021-10-13 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_accounts', '0001_initial'),
        ('meal_ingredients', '0002_mealingredient_code_meal'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealingredient',
            name='code_user_account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='meal_ingredient', to='user_accounts.useraccountname'),
        ),
        migrations.AddConstraint(
            model_name='mealingredient',
            constraint=models.UniqueConstraint(fields=('code_meal', 'code_ingredient'), name='ingredient_meal_unique'),
        ),
    ]
