# Generated by Django 3.2.7 on 2021-11-22 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_ingredients', '0002_mealingredient_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealingredient',
            name='measurement_type',
            field=models.CharField(blank=True, choices=[('', ''), ('g', 'gram'), ('kg', 'kilograms'), ('dp', 'dash/pinch'), ('tsp', 'teaspoon'), ('tbsp', 'tablespoon'), ('c', 'cup'), ('ml', 'millilitre'), ('l', 'litre'), ('bag', 'bag'), ('pack', 'pack')], default='', max_length=5, null=True),
        ),
    ]
