# Generated by Django 3.2.7 on 2021-09-17 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingredients', '0001_initial'),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement_value', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('measurement_type', models.CharField(blank=True, choices=[('', ''), ('g', 'grams'), ('kg', 'kilograms'), ('dash/pinch', 'dash/pinch'), ('tsp', 'teaspoons'), ('tbsp', 'tablespoons'), ('c', 'cups'), ('l', 'litres'), ('lb', 'pounds'), ('oz', 'ounces'), ('pt', 'pints'), ('qt', 'quarts'), ('gal', 'gallons')], default='', max_length=50, null=True)),
                ('code_ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipe_item', to='ingredients.ingredient', verbose_name='Ingredient')),
                ('code_recipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipe_item', to='recipes.recipe', verbose_name='Recipe')),
            ],
        ),
    ]
