# Generated by Django 3.2.7 on 2021-09-27 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_ingredients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='description',
            field=models.CharField(blank=True, default='', max_length=40, null=True),
        ),
    ]
