# Generated by Django 3.2.7 on 2021-09-29 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_ingredients', '0002_alter_recipeingredient_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='description',
            new_name='preparation',
        ),
    ]
