# Generated by Django 3.2.7 on 2021-11-26 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient_categories', '0002_ingredientcategory_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientcategory',
            name='order',
            field=models.PositiveIntegerField(default=99),
        ),
    ]
